# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'tablekSrQug.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1036, 585)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 600, 400))
        self.tabWidget.setStyleSheet(u"QTabBar::tab {\n"
"    height: 80px;          /* \ud0ed\uc758 \ub192\uc774 */\n"
"    width: 120px;          /* \ud0ed\uc758 \ud3ed */\n"
"    font-size: 16px;       /* \uae00\uaf34 \ud06c\uae30 */\n"
"}\n"
"QTabBar::tab:selected {\n"
"    background: lightblue; /* \uc120\ud0dd\ub41c \ud0ed \ubc30\uacbd\uc0c9 */\n"
"    font-weight: bold;     /* \uc120\ud0dd\ub41c \ud0ed \uae00\uc790 \uad75\uac8c */\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    background: lightgray; /* \uc120\ud0dd\ub418\uc9c0 \uc54a\uc740 \ud0ed \ubc30\uacbd\uc0c9 */\n"
"}\n"
"QTabBar::tab {\n"
"    writing-mode: horizontal-tb; /* \ud14d\uc2a4\ud2b8 \ubc29\ud5a5\uc744 \uac00\ub85c\ub85c \uc124\uc815 */\n"
"}")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.groupBox = QGroupBox(self.tab_5)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 191, 281))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 191, 131))
        self.label.setPixmap(QPixmap(u"tomatopasta.jpeg"))
        self.label.setScaledContents(True)
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 160, 191, 51))
        font = QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.pushButton_3 = QPushButton(self.groupBox)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(0, 230, 191, 51))
        font1 = QFont()
        font1.setPointSize(20)
        self.pushButton_3.setFont(font1)
        self.groupBox_2 = QGroupBox(self.tab_5)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(210, 10, 191, 281))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(0, 0, 191, 131))
        self.label_3.setPixmap(QPixmap(u"creampasta.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(0, 160, 191, 51))
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.pushButton_4 = QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_4.setFont(font1)
        self.groupBox_3 = QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(410, 10, 191, 281))
        self.label_5 = QLabel(self.groupBox_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 0, 191, 131))
        self.label_5.setPixmap(QPixmap(u"Vongolepasta.jpeg"))
        self.label_5.setScaledContents(True)
        self.label_6 = QLabel(self.groupBox_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 160, 191, 51))
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(Qt.LeftToRight)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.pushButton_5 = QPushButton(self.groupBox_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_5.setFont(font1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.groupBox_5 = QGroupBox(self.tab_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(210, 10, 191, 281))
        self.label_9 = QLabel(self.groupBox_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 0, 191, 131))
        self.label_9.setPixmap(QPixmap(u"combinationpizza.jpeg"))
        self.label_9.setScaledContents(True)
        self.label_10 = QLabel(self.groupBox_5)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 160, 191, 51))
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.pushButton_7 = QPushButton(self.groupBox_5)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_7.setFont(font1)
        self.groupBox_6 = QGroupBox(self.tab_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 191, 281))
        self.label_11 = QLabel(self.groupBox_6)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 0, 191, 131))
        self.label_11.setPixmap(QPixmap(u"pepelonipizza.jpeg"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.groupBox_6)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 160, 191, 51))
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(Qt.LeftToRight)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.pushButton_8 = QPushButton(self.groupBox_6)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_8.setFont(font1)
        self.groupBox_4 = QGroupBox(self.tab_4)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(410, 10, 191, 281))
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 0, 191, 131))
        self.label_13.setPixmap(QPixmap(u"tomatopasta.jpeg"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 160, 191, 51))
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.pushButton_9 = QPushButton(self.groupBox_4)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_9.setFont(font1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_7 = QGroupBox(self.tab_3)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 10, 191, 281))
        self.label_15 = QLabel(self.groupBox_7)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 0, 191, 131))
        self.label_15.setPixmap(QPixmap(u"tenderloinsteak.jpeg"))
        self.label_15.setScaledContents(True)
        self.label_16 = QLabel(self.groupBox_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 160, 191, 51))
        self.label_16.setFont(font)
        self.label_16.setLayoutDirection(Qt.LeftToRight)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.pushButton_10 = QPushButton(self.groupBox_7)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_10.setFont(font1)
        self.groupBox_8 = QGroupBox(self.tab_3)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(210, 10, 191, 281))
        self.label_17 = QLabel(self.groupBox_8)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 0, 191, 131))
        self.label_17.setPixmap(QPixmap(u"sirloinsteak.jpeg"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.groupBox_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 160, 191, 51))
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(Qt.LeftToRight)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.pushButton_11 = QPushButton(self.groupBox_8)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_11.setFont(font1)
        self.groupBox_9 = QGroupBox(self.tab_3)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(410, 10, 191, 281))
        self.label_19 = QLabel(self.groupBox_9)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 0, 191, 131))
        self.label_19.setPixmap(QPixmap(u"tbonesteak.jpeg"))
        self.label_19.setScaledContents(True)
        self.label_20 = QLabel(self.groupBox_9)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(0, 160, 191, 51))
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.pushButton_12 = QPushButton(self.groupBox_9)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_12.setFont(font1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_10 = QGroupBox(self.tab_2)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 10, 191, 281))
        self.label_21 = QLabel(self.groupBox_10)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 0, 191, 131))
        self.label_21.setPixmap(QPixmap(u"coke2.jpeg"))
        self.label_21.setScaledContents(True)
        self.label_22 = QLabel(self.groupBox_10)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 160, 191, 51))
        self.label_22.setFont(font)
        self.label_22.setLayoutDirection(Qt.LeftToRight)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.pushButton_13 = QPushButton(self.groupBox_10)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_13.setFont(font1)
        self.groupBox_11 = QGroupBox(self.tab_2)
        self.groupBox_11.setObjectName(u"groupBox_11")
        self.groupBox_11.setGeometry(QRect(210, 10, 191, 281))
        self.label_23 = QLabel(self.groupBox_11)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 0, 191, 131))
        self.label_23.setPixmap(QPixmap(u"cider.jpeg"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.groupBox_11)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 160, 191, 51))
        self.label_24.setFont(font)
        self.label_24.setLayoutDirection(Qt.LeftToRight)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.pushButton_14 = QPushButton(self.groupBox_11)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_14.setFont(font1)
        self.groupBox_12 = QGroupBox(self.tab_2)
        self.groupBox_12.setObjectName(u"groupBox_12")
        self.groupBox_12.setGeometry(QRect(410, 10, 191, 281))
        self.label_25 = QLabel(self.groupBox_12)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 0, 191, 131))
        self.label_25.setPixmap(QPixmap(u"blueberryade.jpeg"))
        self.label_25.setScaledContents(True)
        self.label_26 = QLabel(self.groupBox_12)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(0, 160, 191, 51))
        self.label_26.setFont(font)
        self.label_26.setLayoutDirection(Qt.LeftToRight)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.pushButton_15 = QPushButton(self.groupBox_12)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(0, 230, 191, 51))
        self.pushButton_15.setFont(font1)
        self.tabWidget.addTab(self.tab_2, "")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(600, 300, 300, 50))
        self.pushButton.setFont(font1)
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(750, 350, 150, 50))
        self.pushButton_2.setFont(font1)
        self.treeWidget = QTreeWidget(self.centralwidget)
        __qtreewidgetitem = QTreeWidgetItem()
        __qtreewidgetitem.setTextAlignment(1, Qt.AlignCenter);
        __qtreewidgetitem.setTextAlignment(0, Qt.AlignCenter);
        self.treeWidget.setHeaderItem(__qtreewidgetitem)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setGeometry(QRect(600, 0, 300, 300))
        self.treeWidget.setColumnCount(2)
        self.treeWidget.header().setMinimumSectionSize(50)
        self.treeWidget.header().setDefaultSectionSize(200)
        self.treeWidget.header().setProperty("showSortIndicator", False)
        self.pushButton_6 = QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(600, 350, 150, 50))
        self.pushButton_6.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\ucd94\ucc9c\uba54\ub274", None))
        self.groupBox.setTitle("")
        self.label.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Tomato Pasta", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_2.setTitle("")
        self.label_3.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Cream Pasta", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_3.setTitle("")
        self.label_5.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Vongole Pasta", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Pasta", None))
        self.groupBox_5.setTitle("")
        self.label_9.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Combination Pizza", None))
        self.pushButton_7.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_6.setTitle("")
        self.label_11.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Pepeloni Pizza", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_4.setTitle("")
        self.label_13.setText("")
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Hawaiian Pizza", None))
        self.pushButton_9.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Pizza", None))
        self.groupBox_7.setTitle("")
        self.label_15.setText("")
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Tenderloin Steak", None))
        self.pushButton_10.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_8.setTitle("")
        self.label_17.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Sirloin Steak", None))
        self.pushButton_11.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_9.setTitle("")
        self.label_19.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"T-bone Steak", None))
        self.pushButton_12.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Steak", None))
        self.groupBox_10.setTitle("")
        self.label_21.setText("")
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Coke", None))
        self.pushButton_13.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_11.setTitle("")
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Cider", None))
        self.pushButton_14.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.groupBox_12.setTitle("")
        self.label_25.setText("")
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Blueberry Ade", None))
        self.pushButton_15.setText(QCoreApplication.translate("MainWindow", u"\uc120    \ud0dd", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Drink", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"\uc8fc    \ubb38", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(1, QCoreApplication.translate("MainWindow", u"\uc218\ub7c9", None));
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"menu", None));
        self.pushButton_6.setText(QCoreApplication.translate("MainWindow", u"\ucde8\uc18c", None))
    # retranslateUi

